nameOverride: ""
fullnameOverride: ""

controller:

  image:
    repository: quay.io/acoustid/linstor-controller
    tag: master
    pullPolicy: Always

  affinity: {}

node:

  satellite:
    image:
      repository: quay.io/acoustid/linstor-satellite
      tag: master
      pullPolicy: Always

  csi:
    image:
      repository: quay.io/acoustid/linstor-csi
      tag: master
      pullPolicy: Always

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/storage
              operator: In
              values:
                - "true"
