FROM ubuntu:bionic

ARG DRBD_VERSION=9.0.21-1

RUN apt-get update && apt-get install -y kmod gnupg wget make gcc patch curl

RUN wget https://www.linbit.com/downloads/drbd/9.0/drbd-${DRBD_VERSION}.tar.gz -O /drbd.tar.gz

COPY /entry.sh /
RUN chmod +x /entry.sh

ENTRYPOINT /entry.sh
