name: Build
on: [push]
jobs:

  docker-drdb-bionic:
    name: Build image drbd:bionic
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Build image
        run: |
          cd images/drbd/
          docker build -f Dockerfile.bionic -t quay.io/acoustid/drbd:bionic .

  docker-drdb-centos7:
    name: Build image drbd:centos7
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Build image
        run: |
          cd images/drbd/
          docker build -f Dockerfile.centos7 -t quay.io/acoustid/drbd:centos7 .

  docker-drdb-centos8:
    name: Build image drbd:centos8
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Build image
        run: |
          cd images/drbd/
          docker build -f Dockerfile.centos8 -t quay.io/acoustid/drbd:centos8 .

  docker-linstor-client:
    name: Build image linstor-client
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Build image
        run: |
          cd images/linstor-client/
          docker build -f Dockerfile -t quay.io/acoustid/linstor-client .

  docker-linstor-controller:
    name: Build image linstor-controller
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Build image
        run: |
          cd images/linstor-controller/
          docker build -f Dockerfile -t quay.io/acoustid/linstor-controller .

  docker-linstor-satellite:
    name: Build image linstor-satellite
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Build image
        run: |
          cd images/linstor-satellite/
          docker build -f Dockerfile -t docker.pkg.github.com/acoustid/k8s-linstor/linstor-satellite:$GITHUB_SHA .
      - name: Push image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
          docker push docker.pkg.github.com/acoustid/k8s-linstor/linstor-satellite:$GITHUB_SHA
