name: Build images
on:
  push:
    paths:
      - images/**
jobs:

  build-images:
    name: Build images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - drbd
          - linstor-client
          - linstor-controller
          - linstor-satellite
          - linstor-csi
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Set GITHUB_REF_SLUG
        run: echo ::set-env name=GITHUB_REF_SLUG::$(echo $GITHUB_REF | cut -d'/' -f3)
      - name: Build image
        run: |
          cd images/${{ matrix.component }}/
          docker build -t quay.io/acoustid/${{ matrix.component }}:$GITHUB_REF_SLUG .
      - name: Push image
        run: |
          echo ${{ secrets.QUAY_PASSWORD }} | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin
          docker push quay.io/acoustid/${{ matrix.component }}:$GITHUB_REF_SLUG
