name: Build
on: [push]
jobs:

  docker-drbd:
    name: Build drbd images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - bionic
          - centos7
          - centos8
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Set GITHUB_REF_SLUG
        run: echo ::set-env name=GITHUB_REF_SLUG::$(echo $GITHUB_REF | cut -d'/' -f3)
      - name: Build image
        run: |
          cd images/drbd/
          docker build -f Dockerfile.bionic -t docker.pkg.github.com/$GITHUB_REPOSITORY/drbd:$GITHUB_REF_SLUG-${{ matrix.distro }} .
      - name: Push image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/drbd:$GITHUB_REF_SLUG-${{ matrix.distro }}

  docker-linstor:
    name: Build linstor images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - client
          - controller
          - satellite
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Set GITHUB_REF_SLUG
        run: echo ::set-env name=GITHUB_REF_SLUG::$(echo $GITHUB_REF | cut -d'/' -f3)
      - name: Build image
        run: |
          cd images/linstor-${{ matrix.component }}/
          docker build -f Dockerfile -t docker.pkg.github.com/$GITHUB_REPOSITORY/linstor-${{ matrix.component }}:$GITHUB_REF_SLUG .
      - name: Push image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/linstor-${{ matrix.component }}:$GITHUB_REF_SLUG
